version: '3'
services:

  app:
    restart: always
    image: parser
    container_name: parser
#    links:
#      - rabbitmq
#      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/price_parser
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=price_parser

  rabbitmq:
    restart: always
    image: rabbitmq:3.7.5-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
